### ISSUE TITLE
Various Support

### ISSUE THREAD

**Issue by whomstdve-haveth-pinged-me** [Finchiedev/UniversalRecipes#4]
**Is your feature request related to a problem? Please describe.**

I’m always frustrated when the mods are gay. This sort of homosexual behaviour is not at all appropriate for a serious project such as this.

**Describe the solution you'd like**

These mods should quit github, go to the laundry and well... I think you know what to do with various cleaning products
**Describe alternatives you've considered**

Slitting the y335 our of them
**Additional context**

**Comment by Finchiedev** [comment]
**Please do not spam**
